import 'package:beauty_call/utils/vender_theme/strings.dart';

class Doctor {
  String imageUrl, name, designation, condition, review;

  Doctor(
      {this.imageUrl,
      this.name,
      this.designation,
      this.condition,
      this.review});
}

class DoctorData {
  static List<Doctor> allDoctorList = [
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
  ];

  static List<Doctor> cardioDoctorList = [
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
  ];

  static List<Doctor> heartDoctorList = [
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
  ];

  static List<Doctor> mentalDoctorList = [
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
  ];

  static List<Doctor> dentalDoctorList = [
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_NATIONAL_HEART_CENTER,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.CARDIO_SURGEON_NATIONAL_CARDILOGY_CARE,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.DENTIST_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.CONSULTANT_NATIONAL_DENTAL_AND,
      review: Strings.REVIEW_4,
      condition: Strings.AVAILABLE,
    ),
  ];

  static List<Doctor> topDoctorList = [
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_SPACIALIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor4.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_SPACIALIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_SPACIALIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor4.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_SPACIALIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor1.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_SPACIALIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor2.jpg',
      name: Strings.DOCTOR_NAME2,
      designation: Strings.CARDIO_SURGEON,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor3.jpg',
      name: Strings.DOCTOR_NAME3,
      designation: Strings.DENTIST,
    ),
    Doctor(
      imageUrl: 'assets/doctor/images/doctor4.jpg',
      name: Strings.DOCTOR_NAME1,
      designation: Strings.HEART_SURGEON_SPACIALIST,
    ),
  ];
}
